# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807c08ba225029da2a6812cd8ed6992440398d6045e192ecb2ef7e07bd7545449f62b4c42a901244b459a3778ed696d95dd2534ccb71edc0b60c2d16f28fe113

test:
  secret_key_base: e75d9fc9ab7546b194e90ce970ab0050842b6934631bf73bb69cf17ca5c82ab7806698278d6355275bd79c94cc1a2b0ff9e113a16bee66cc00918935cb06a2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
